version: "3.9"

services:
  django:
    build: .
    container_name: django_chat
    #command: daphne -b 0.0.0.0 -p 8000 django_chat_classifier.asgi:application
    command: watchmedo auto-restart --directory=./ --pattern="*.py" --recursive -- daphne -b 0.0.0.0 -p 8000 django_chat_classifier.asgi:application

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=django_chat_classifier.settings
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_chat
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
